image: node:latest

stages:
  - install
  - build
  - deploy

before_script:
  - apt-get update -qq && apt-get install

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install
  only:
    - master

build:
  stage: build
  script:
    - yarn build
  only:
    - master
  dependencies:
    - install

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - yarn aws-deploy
    - yarn aws-cache-clear
  only:
    - master
