stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .yarn

test:
  image: node:latest
  stage: test
  before_script:
    - apt-get update -qq && apt-get install
    - yarn config set cache-folder .yarn
    - yarn insall
    - export REACT_APP_KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
    - export REACT_APP_KAKAO_OAUTH_URL=$KAKAO_OAUTH_URL
  script:
    - yarn test
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" ||  $CI_COMMIT_REF_NAME == "dev"
      when: always

build/product:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install
    - yarn config set cache-folder .yarn
    - yarn insall
    - export REACT_APP_KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
    - export REACT_APP_KAKAO_OAUTH_URL=$KAKAO_OAUTH_URL
  script:
    - yarn build
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: on_success

build/proto:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install
    - yarn config set cache-folder .yarn
    - yarn insall
    - export REACT_APP_KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
    - export REACT_APP_KAKAO_OAUTH_URL=$KAKAO_OAUTH_URL
  script:
    - yarn build
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: on_success

deploy/product:
  image: python:latest
  stage: deploy
  variables:
    S3_BUCKET_NAME: ddakdae-client
    CF_DISTRIBUTION_ID: E1UCZ1564QEQI0
  script:
    - pip install awscli
    - aws s3 sync build s3://$S3_BUCKET_NAME/
  after_script:
    - aws cloudfront create-invalidation --distribution-id=$CF_DISTRIBUTION_ID --paths '/*'
  dependencies:
    - build/product
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: on_success

deploy/proto:
  image: python:latest
  stage: deploy
  variables:
    S3_BUCKET_NAME: ddakdae-client-proto
  before_script:
    - pip install awscli
  script:
    - aws s3 sync build s3://$S3_BUCKET_NAME/ --acl public-read
  dependencies:
    - build/proto
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: on_success
