image: node:latest

stages:
  - install
  - build
  - deploy

before_script:
  - apt-get update -qq && apt-get install

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install
  only:
    - master

build:
  stage: build
  script:
    - yarn build
  only:
    - master
  dependencies:
    - install
  artifacts:
    paths:
        - build/

variables:
  S3_BUCKET_NAME: ddakdae-client
  CF_DISTRIBUTION_ID: E1UCZ1564QEQI0
deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync build/ s3://$S3_BUCKET_NAME/
    - aws cloudfront create-invalidation --distribution-id=$CF_DISTRIBUTION_ID --paths '/*

  only:
    - master
