image: node:latest

stages:
  - install
  - build
  - quality
  - deploy

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

install:
  stage: install
  script:
    - apt-get update -qq && apt-get install
    - yarn config set cache-folder .yarn
    - yarn install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .yarn/
      - node_modules/
      - cache/Cypress
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: always
    - when: never

build:
  stage: build
  dependencies:
    - install
  before_script:
    - export REACT_APP_KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
    - export REACT_APP_KAKAO_OAUTH_URL=$KAKAO_OAUTH_URL
  script:
    - yarn build
  artifacts:
    paths:
      - build
    expire_in: 30 mins
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: on_success
    - when: never

test/unit:
  stage: quality
  dependencies:
    - install
  before_script:
    - export REACT_APP_KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
    - export REACT_APP_KAKAO_OAUTH_URL=$KAKAO_OAUTH_URL
  script:
    - yarn unit-test
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: on_success
    - when: never

test/e2e:
  image: cypress/base:10
  stage: quality
  dependencies:
    - install
    - build
  before_script:
    - export REACT_APP_KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
    - export REACT_APP_KAKAO_OAUTH_URL=$KAKAO_OAUTH_URL
  script:
    - yarn e2e-test
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: on_success
    - when: never

deploy/product:
  image: python:latest
  stage: deploy
  dependencies:
    - build
  variables:
    S3_BUCKET_NAME: ddakdae-client
    CF_DISTRIBUTION_ID: E1UCZ1564QEQI0
  before_script:
    - pip install awscli
  script:
    - aws s3 sync build s3://$S3_BUCKET_NAME/
  after_script:
    - aws cloudfront create-invalidation --distribution-id=$CF_DISTRIBUTION_ID --paths '/*'
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: on_success
    - when: never

deploy/proto:
  image: python:latest
  stage: deploy
  dependencies:
    - build
  variables:
    S3_PROTO_BUCKET_NAME: ddakdae-client-proto
  before_script:
    - pip install awscli
  script:
    - aws s3 sync build s3://$S3_PROTO_BUCKET_NAME/ --acl public-read
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: never
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: on_success
    - when: never
